# Generated by Django 2.0.6 on 2018-06-21 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('lot_number', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('description_text', models.CharField(max_length=128)),
                ('purchaseDate_date', models.DateField()),
                ('received_boolean', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku_number', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('categories_text', models.CharField(max_length=256)),
                ('descriptionShort_text', models.CharField(max_length=80)),
                ('weight_number', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lot_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Lot')),
            ],
        ),
    ]
