# Generated by Django 2.0.6 on 2018-08-25 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('purchase_date', models.DateField()),
                ('received', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=256)),
                ('short_description', models.CharField(max_length=80)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Lot')),
            ],
        ),
    ]
